version: '3.9'
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'UTC'
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
